---

- name: restart rsyslog
  service: name=rsyslog state=restarted enabled=yes

- name: restart ntpdate
  service: name=ntpdate.service state=restarted enabled=yes

- name: restart htpdate
  service: name=htpdate.service state=restarted enabled=yes

- name: reload systemd
  systemd: daemon_reload=yes
